function Suma() {
    var d1 = prompt("Ingrasa el primer número: ")
    var d2 = prompt("Ingresa el segundo número: ")
    var res = parseInt(d1) + parseInt(d2)
    alert("El resultado es: " + res)
}

function Resta() {
    var d1 = prompt('Ingrasa el primer número: ');
    var d2 = prompt('Ingresa el segundo número: ');
    var res = parseInt(d1) - parseInt(d2);
    alert('El resultado es: ' + res);
}

function Multiplicacion() {
    var d1 = prompt('Ingrasa el primer número: ');
    var d2 = prompt('Ingresa el segundo número: ');
    var res = parseInt(d1) * parseInt(d2);
    alert('El resultado es: ' + res);
}

function Division() {
    var d1 = prompt('Ingrasa el primer número: ');
    var d2 = prompt('Ingresa el segundo número: ');
    var res = parseInt(d1) / parseInt(d2);
    alert('El resultado es: ' + res);
}